steps:
  - name: Intall python
    args:
      - install
      - '-r'
      - requirements.txt
      - '--user'
    entrypoint: pip
  - name: Run Historical Load
    args:
      - bq_historical_load.py
      - trigger/dev/Historical_Load_partition_info.txt
      - $_CONFIG_PROJECTNAME
      - config/dev/Historical_Load_config.json
      - $_CONFIG_DATASET
    entrypoint: python
